#include "iostream"
using namespace std;
int T,a2,a3,a4,b4,b6;
int main(){
    cin>>T;
    while(T--){
        cin>>a2>>a3>>a4>>b4>>b6;
        int res=0;
        while(b4>0&&a4>0){
            a4--;
            b4--;
            res+=4;
        }
        while(b6>0&&a2>0&&a4>0){
            a4--;
            a2--;
            b6--;
            res+=6;
        }
        while(b4>0&&a2-1>0){
            a2-=2;b4--;
            res+=4;
        }
        while(b6>0&&a3-1>0){
            a3-=2;
            b6--;
            res+=6;
        }
        while(b6>0&&a2-2>0){
            a2-=3;
            b6--;
            res+=6;
        }
        while(b4>0&&a3>0){
            a3--;
            b4--;
            res+=3;
        }
        while(b6>0&&a3>0&&a2>0){
            a3--;
            a2--;
            b6--;
            res+=5;
        }
        while(b6>0&&a2-1>0){
            a2-=2;
            b6--;
            res+=4;
        }
        while(b4>0&&a2>0){
            a2--;
            b4--;
            res+=2;
        }
        while(b6>0&&a4>0){
            a4--;
            b6--;
            res+=4;
        }
        while(b6>0&&a3>0){
            a3--;
            b6--;
            res+=3;
        }
        while(b6>0&&a2>0){
            a2--;
            b6--;
            res+=2;
        }
        cout<<res<<endl;
    }
}